approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - vitest
  - '@vitest/*'

yarnPath: .yarn/releases/yarn-4.17.1.cjs
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vitest: 4.1.10
  vite-plus: 0.2.5
  '@vitest/ui': 4.1.10
