import { defineConfig } from 'vite-plus';

export default defineConfig({
  lint: {
    // .storybook/** is deliberately outside the packages' tsconfig `include`
    // (see exclude: ["**/.*"]), so type-aware rules would run there without
    // the project's compiler options and report spurious errors.
    // `scripts/**` was in the old ESLint `ignores` list too — these are
    // one-off codegen scripts, not shipped source.
    // `*.gen.ts` files are generated by hey-api (`yarn lib gen:sdk`) and must
    // not be edited by hand, so their warnings can't be fixed. Patterns match
    // paths relative to where lint runs, hence a file-name pattern.
    ignorePatterns: ['**/.storybook/**', 'scripts/**', '**/*.gen.ts'],
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'import'],
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin'
      }
    ],
    categories: {
      correctness: 'warn'
    },
    // The migration inlined ~1100 lines of individual browser globals here.
    // These env flags are equivalent (and match the old .eslintrc `env`),
    // verified to produce byte-identical lint results.
    env: {
      browser: true,
      builtin: true,
      commonjs: true,
      es2020: true,
      jest: true,
      node: true
    },
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'off',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'react/rules-of-hooks': 'error',
      'typescript/ban-ts-comment': 'off',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'off',
      'typescript/no-explicit-any': 'off',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error'
    },
    overrides: [
      {
        // Storybook story `render` functions are anonymous components, which
        // legitimately trips rules-of-hooks.
        files: ['**/*.stories.tsx'],
        rules: {
          'react/rules-of-hooks': 'off'
        }
      },
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error'
        }
      }
    ],
    options: {
      typeAware: true,
      typeCheck: true
    }
  },
  fmt: {
    semi: true,
    singleQuote: true,
    trailingComma: 'none',
    bracketSameLine: true,
    printWidth: 80,
    sortPackageJson: false,
    // release-please writes the changelog, in its own format.
    ignorePatterns: ['CHANGELOG.md']
  }
});
