// This file is auto-generated by @hey-api/openapi-ts

export const AnnotationSchema = {
  type: 'object',
  required: ['description', 'version'],
  properties: {
    description: {
      type: 'string'
    },
    version: {
      type: 'string'
    }
  }
} as const;

export const ComponentPropertiesSchema = {
  type: 'object',
  required: ['image', 'metadata'],
  properties: {
    image: {
      type: 'string'
    },
    metadata: {
      $ref: '#/components/schemas/WorkflowStepMetadata'
    },
    parameters: {
      type: ['object', 'null'],
      additionalProperties: {},
      propertyNames: {
        type: 'string'
      }
    }
  }
} as const;

export const CreateNodeInputSchemaSchema = {
  type: 'object',
  required: ['node_def', 'wasm_file', 'icon'],
  properties: {
    icon: {
      type: 'string',
      format: 'binary'
    },
    node_def: {
      $ref: '#/components/schemas/NodeDef'
    },
    wasm_file: {
      type: 'string',
      format: 'binary'
    }
  }
} as const;

export const CreateWorkflowSchema = {
  type: 'object',
  required: ['workflow_def'],
  properties: {
    workflow_def: {
      $ref: '#/components/schemas/WorkflowDef'
    }
  }
} as const;

export const DeploymentSchema = {
  type: 'object',
  required: ['deployment_id', 'workflow_id', 'status'],
  properties: {
    deployment_id: {
      type: 'string'
    },
    manifest_name: {
      type: ['string', 'null']
    },
    manifest_version: {
      type: ['string', 'null']
    },
    status: {
      type: 'string',
      enum: [
        'Created',
        'Submitted',
        'Validated',
        'Processed',
        'Deployed',
        'Cancelled'
      ]
    },
    workflow_id: {
      type: 'string'
    }
  }
} as const;

export const DeploymentsSchema = {
  type: 'array',
  items: {
    $ref: '#/components/schemas/Deployment'
  }
} as const;

export const ErrorTypeSchema = {
  oneOf: [
    {
      type: 'object',
      required: ['type'],
      properties: {
        type: {
          type: 'string',
          enum: ['NotFound']
        }
      }
    },
    {
      type: 'object',
      required: ['type'],
      properties: {
        type: {
          type: 'string',
          enum: ['BadRequest']
        }
      }
    },
    {
      type: 'object',
      required: ['type'],
      properties: {
        type: {
          type: 'string',
          enum: ['InternalServerError']
        }
      }
    },
    {
      type: 'object',
      required: ['type'],
      properties: {
        type: {
          type: 'string',
          enum: ['Conflict']
        }
      }
    },
    {
      type: 'object',
      required: ['type'],
      properties: {
        type: {
          type: 'string',
          enum: ['Unauthorized']
        }
      }
    },
    {
      type: 'object',
      required: ['type'],
      properties: {
        type: {
          type: 'string',
          enum: ['WorkflowNotDeployed']
        }
      }
    }
  ]
} as const;

export const ExecutionsSchema = {
  type: 'array',
  items: {
    $ref: '#/components/schemas/Model'
  }
} as const;

export const HashMapSchema = {
  type: 'object',
  additionalProperties: {
    type: 'array',
    items: {
      type: 'string'
    }
  },
  propertyNames: {
    type: 'string'
  }
} as const;

export const MetadataSchema = {
  type: 'object',
  required: ['name'],
  properties: {
    annotations: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/Annotation'
        }
      ]
    },
    name: {
      type: 'string'
    }
  }
} as const;

export const ModelSchema = {
  type: 'object',
  required: [
    'id',
    'workflow_id',
    'run_id',
    'started',
    'status',
    'created_at',
    'updated_at'
  ],
  properties: {
    created_at: {
      type: 'string',
      format: 'date-time'
    },
    id: {
      type: 'string',
      format: 'uuid'
    },
    result: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/Value'
        }
      ]
    },
    run_id: {
      type: 'string'
    },
    started: {
      type: 'boolean'
    },
    status: {
      type: 'string'
    },
    updated_at: {
      type: 'string',
      format: 'date-time'
    },
    workflow_id: {
      type: 'string',
      format: 'uuid'
    }
  }
} as const;

export const NodeAnnotationSchema = {
  type: 'object',
  required: ['description', 'version', 'label', 'icon', 'color', 'ui'],
  properties: {
    color: {
      type: 'string'
    },
    description: {
      type: 'string'
    },
    icon: {
      type: 'string'
    },
    label: {
      type: 'string'
    },
    ui: {
      type: 'string'
    },
    version: {
      type: 'string'
    }
  }
} as const;

export const NodeDefSchema = {
  type: 'object',
  required: ['api_version', 'metadata', 'spec'],
  properties: {
    api_version: {
      type: 'string'
    },
    metadata: {
      $ref: '#/components/schemas/NodeMetadata'
    },
    spec: {
      $ref: '#/components/schemas/NodeSpec'
    }
  }
} as const;

export const NodeMetadataSchema = {
  type: 'object',
  required: ['name', 'annotations'],
  properties: {
    annotations: {
      $ref: '#/components/schemas/NodeAnnotation'
    },
    name: {
      type: 'string'
    }
  }
} as const;

export const NodeModelSchema = {
  type: 'object',
  required: ['id', 'node_def', 'image', 'created_at', 'updated_at'],
  properties: {
    created_at: {
      type: 'string',
      format: 'date-time'
    },
    id: {
      type: 'string',
      format: 'uuid'
    },
    image: {
      type: 'string'
    },
    node_def: {
      $ref: '#/components/schemas/NodeDef'
    },
    updated_at: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const NodeModelsSchema = {
  type: 'array',
  items: {
    $ref: '#/components/schemas/NodeModel'
  }
} as const;

export const NodeParameterSchema = {
  oneOf: [
    {
      type: 'object',
      required: ['description', 'default', 'type'],
      properties: {
        default: {
          type: 'string'
        },
        description: {
          type: 'string'
        },
        type: {
          type: 'string',
          enum: ['string']
        }
      }
    },
    {
      type: 'object',
      required: ['description', 'default', 'type'],
      properties: {
        default: {
          type: 'number',
          format: 'float'
        },
        description: {
          type: 'string'
        },
        type: {
          type: 'string',
          enum: ['number']
        }
      }
    },
    {
      type: 'object',
      required: ['description', 'default', 'type'],
      properties: {
        default: {
          type: 'integer',
          format: 'int32'
        },
        description: {
          type: 'string'
        },
        type: {
          type: 'string',
          enum: ['integer']
        }
      }
    },
    {
      type: 'object',
      required: ['description', 'default', 'type'],
      properties: {
        default: {
          type: 'boolean'
        },
        description: {
          type: 'string'
        },
        type: {
          type: 'string',
          enum: ['boolean']
        }
      }
    },
    {
      type: 'object',
      required: ['description', 'default', 'type'],
      properties: {
        default: {
          type: 'object',
          additionalProperties: {
            type: 'string'
          },
          propertyNames: {
            type: 'string'
          }
        },
        description: {
          type: 'string'
        },
        type: {
          type: 'string',
          enum: ['object']
        }
      }
    },
    {
      type: 'object',
      required: ['description', 'default', 'type'],
      properties: {
        default: {
          type: 'array',
          items: {
            type: 'string'
          }
        },
        description: {
          type: 'string'
        },
        type: {
          type: 'string',
          enum: ['array']
        }
      }
    }
  ]
} as const;

export const NodeParameterDefinitionSchema = {
  type: 'object',
  required: ['validation_schema'],
  properties: {
    validation_schema: {
      $ref: '#/components/schemas/ValidationSchema'
    }
  }
} as const;

export const NodeSpecSchema = {
  type: 'object',
  required: ['properties'],
  properties: {
    properties: {
      $ref: '#/components/schemas/Properties'
    }
  }
} as const;

export const OpenApiErrorSchema = {
  allOf: [
    {
      $ref: '#/components/schemas/ErrorType'
    },
    {
      type: 'object',
      required: ['message'],
      properties: {
        details: {
          oneOf: [
            {
              type: 'null'
            },
            {
              $ref: '#/components/schemas/HashMap'
            }
          ]
        },
        message: {
          type: 'string'
        }
      }
    }
  ]
} as const;

export const PositionSchema = {
  type: 'object',
  required: ['x', 'y'],
  properties: {
    x: {
      type: 'number',
      format: 'float'
    },
    y: {
      type: 'number',
      format: 'float'
    }
  }
} as const;

export const PropertiesSchema = {
  type: 'object',
  required: ['parameters'],
  properties: {
    parameters: {
      $ref: '#/components/schemas/NodeParameterDefinition'
    }
  }
} as const;

export const ProviderPropertiesSchema = {
  type: 'object',
  required: ['image'],
  properties: {
    image: {
      type: 'string'
    }
  }
} as const;

export const SuccessResponseSchema = {
  type: 'object',
  required: ['success'],
  properties: {
    success: {
      type: 'boolean'
    }
  }
} as const;

export const UpdateWorkflowSchema = {
  type: 'object',
  required: ['workflow_def'],
  properties: {
    workflow_def: {
      $ref: '#/components/schemas/WorkflowDef'
    }
  }
} as const;

export const ValidationSchemaSchema = {
  type: 'object',
  required: ['properties', 'required'],
  properties: {
    properties: {
      type: 'object',
      additionalProperties: {
        $ref: '#/components/schemas/NodeParameter'
      },
      propertyNames: {
        type: 'string'
      }
    },
    required: {
      type: 'array',
      items: {
        type: 'string'
      }
    }
  }
} as const;

export const ValueSchema = {} as const;

export const WorkflowDefSchema = {
  type: 'object',
  required: ['api_version', 'metadata', 'spec'],
  properties: {
    api_version: {
      type: 'string'
    },
    metadata: {
      $ref: '#/components/schemas/Metadata'
    },
    spec: {
      $ref: '#/components/schemas/WorkflowSpec'
    }
  }
} as const;

export const WorkflowModelSchema = {
  type: 'object',
  required: ['id', 'workflow_def', 'created_at', 'updated_at'],
  properties: {
    created_at: {
      type: 'string',
      format: 'date-time'
    },
    deployment_id: {
      type: ['string', 'null'],
      format: 'uuid'
    },
    id: {
      type: 'string',
      format: 'uuid'
    },
    manifest_name: {
      type: ['string', 'null']
    },
    updated_at: {
      type: 'string',
      format: 'date-time'
    },
    workflow_def: {
      $ref: '#/components/schemas/WorkflowDef'
    }
  }
} as const;

export const WorkflowModelsSchema = {
  type: 'array',
  items: {
    $ref: '#/components/schemas/WorkflowModel'
  }
} as const;

export const WorkflowSpecSchema = {
  type: 'object',
  required: ['drafts', 'steps'],
  properties: {
    drafts: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/WorkflowStep'
      }
    },
    steps: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/WorkflowStep'
      }
    }
  }
} as const;

export const WorkflowStepSchema = {
  allOf: [
    {
      $ref: '#/components/schemas/WorkflowStepProperties'
    },
    {
      type: 'object',
      required: ['name'],
      properties: {
        name: {
          type: 'string'
        }
      }
    }
  ]
} as const;

export const WorkflowStepMetadataSchema = {
  type: 'object',
  required: ['position'],
  properties: {
    position: {
      $ref: '#/components/schemas/Position'
    }
  }
} as const;

export const WorkflowStepPropertiesSchema = {
  oneOf: [
    {
      type: 'object',
      required: ['properties', 'type'],
      properties: {
        properties: {
          $ref: '#/components/schemas/ComponentProperties'
        },
        type: {
          type: 'string',
          enum: ['component']
        }
      }
    },
    {
      type: 'object',
      required: ['properties', 'type'],
      properties: {
        properties: {
          $ref: '#/components/schemas/ProviderProperties'
        },
        type: {
          type: 'string',
          enum: ['provider']
        }
      }
    }
  ]
} as const;
