// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer
} from '@hey-api/client-axios';
import type {
  ListDeploymentsData,
  ListDeploymentsResponse,
  ListDeploymentsError,
  DeleteDeploymentData,
  DeleteDeploymentResponse,
  DeleteDeploymentError,
  GetDeploymentData,
  GetDeploymentResponse,
  GetDeploymentError,
  ListExecutionsData,
  ListExecutionsResponse,
  ListExecutionsError,
  DeleteExecutionsData,
  DeleteExecutionsResponse,
  DeleteExecutionsError,
  GetExecutionData,
  GetExecutionResponse,
  GetExecutionError,
  ListNodesData,
  ListNodesResponse,
  ListNodesError,
  CreateNodeData,
  CreateNodeResponse,
  CreateNodeError,
  GetNodeByIdData,
  GetNodeByIdResponse,
  GetNodeByIdError,
  ListWorkflowsData,
  ListWorkflowsResponse,
  ListWorkflowsError,
  CreateWorkflowData,
  CreateWorkflowResponse,
  CreateWorkflowError,
  DeleteWorkflowData,
  DeleteWorkflowResponse,
  DeleteWorkflowError,
  GetWorkflowByIdData,
  GetWorkflowByIdResponse,
  GetWorkflowByIdError,
  UpdateWorkflowData,
  UpdateWorkflowResponse,
  UpdateWorkflowError,
  DeployWorkflowData,
  DeployWorkflowResponse,
  DeployWorkflowError,
  RunWorkflowData,
  RunWorkflowResponse,
  RunWorkflowError
} from './types.gen';
import { client as _heyApiClient } from './client.gen';
import {
  listExecutionsResponseTransformer,
  getExecutionResponseTransformer,
  listNodesResponseTransformer,
  createNodeResponseTransformer,
  getNodeByIdResponseTransformer,
  listWorkflowsResponseTransformer,
  createWorkflowResponseTransformer,
  getWorkflowByIdResponseTransformer,
  updateWorkflowResponseTransformer
} from './transformers.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const listDeployments = <ThrowOnError extends boolean = false>(
  options?: Options<ListDeploymentsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDeploymentsResponse,
    ListDeploymentsError,
    ThrowOnError
  >({
    url: '/api/v1/deployments',
    ...options
  });
};

export const deleteDeployment = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDeploymentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDeploymentResponse,
    DeleteDeploymentError,
    ThrowOnError
  >({
    url: '/api/v1/deployments/{id}',
    ...options
  });
};

export const getDeployment = <ThrowOnError extends boolean = false>(
  options: Options<GetDeploymentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetDeploymentResponse,
    GetDeploymentError,
    ThrowOnError
  >({
    url: '/api/v1/deployments/{id}',
    ...options
  });
};

export const listExecutions = <ThrowOnError extends boolean = false>(
  options?: Options<ListExecutionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListExecutionsResponse,
    ListExecutionsError,
    ThrowOnError
  >({
    responseTransformer: listExecutionsResponseTransformer,
    url: '/api/v1/executions',
    ...options
  });
};

export const deleteExecutions = <ThrowOnError extends boolean = false>(
  options: Options<DeleteExecutionsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteExecutionsResponse,
    DeleteExecutionsError,
    ThrowOnError
  >({
    url: '/api/v1/executions/{id}',
    ...options
  });
};

export const getExecution = <ThrowOnError extends boolean = false>(
  options: Options<GetExecutionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetExecutionResponse,
    GetExecutionError,
    ThrowOnError
  >({
    responseTransformer: getExecutionResponseTransformer,
    url: '/api/v1/executions/{id}',
    ...options
  });
};

export const listNodes = <ThrowOnError extends boolean = false>(
  options?: Options<ListNodesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListNodesResponse,
    ListNodesError,
    ThrowOnError
  >({
    responseTransformer: listNodesResponseTransformer,
    url: '/api/v1/nodes',
    ...options
  });
};

export const createNode = <ThrowOnError extends boolean = false>(
  options: Options<CreateNodeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateNodeResponse,
    CreateNodeError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseTransformer: createNodeResponseTransformer,
    url: '/api/v1/nodes',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers
    }
  });
};

export const getNodeById = <ThrowOnError extends boolean = false>(
  options: Options<GetNodeByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetNodeByIdResponse,
    GetNodeByIdError,
    ThrowOnError
  >({
    responseTransformer: getNodeByIdResponseTransformer,
    url: '/api/v1/nodes/{id}',
    ...options
  });
};

export const listWorkflows = <ThrowOnError extends boolean = false>(
  options?: Options<ListWorkflowsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListWorkflowsResponse,
    ListWorkflowsError,
    ThrowOnError
  >({
    responseTransformer: listWorkflowsResponseTransformer,
    url: '/api/v1/workflows',
    ...options
  });
};

export const createWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<CreateWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateWorkflowResponse,
    CreateWorkflowError,
    ThrowOnError
  >({
    responseTransformer: createWorkflowResponseTransformer,
    url: '/api/v1/workflows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers
    }
  });
};

export const deleteWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteWorkflowResponse,
    DeleteWorkflowError,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{id}',
    ...options
  });
};

export const getWorkflowById = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkflowByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetWorkflowByIdResponse,
    GetWorkflowByIdError,
    ThrowOnError
  >({
    responseTransformer: getWorkflowByIdResponseTransformer,
    url: '/api/v1/workflows/{id}',
    ...options
  });
};

export const updateWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateWorkflowResponse,
    UpdateWorkflowError,
    ThrowOnError
  >({
    responseTransformer: updateWorkflowResponseTransformer,
    url: '/api/v1/workflows/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers
    }
  });
};

export const deployWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<DeployWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    DeployWorkflowResponse,
    DeployWorkflowError,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{id}/deploy',
    ...options
  });
};

export const runWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<RunWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    RunWorkflowResponse,
    RunWorkflowError,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{id}/run',
    ...options
  });
};
