// This file is auto-generated by @hey-api/openapi-ts

import type {
  ListExecutionsResponse,
  GetExecutionResponse,
  ListNodesResponse,
  CreateNodeResponse,
  GetNodeByIdResponse,
  ListWorkflowsResponse,
  CreateWorkflowResponse,
  GetWorkflowByIdResponse,
  UpdateWorkflowResponse
} from './types.gen';

const modelSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const executionsSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => {
    return modelSchemaResponseTransformer(item);
  });
  return data;
};

export const listExecutionsResponseTransformer = async (
  data: any
): Promise<ListExecutionsResponse> => {
  data = executionsSchemaResponseTransformer(data);
  return data;
};

export const getExecutionResponseTransformer = async (
  data: any
): Promise<GetExecutionResponse> => {
  data = modelSchemaResponseTransformer(data);
  return data;
};

const nodeModelSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const nodeModelsSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => {
    return nodeModelSchemaResponseTransformer(item);
  });
  return data;
};

export const listNodesResponseTransformer = async (
  data: any
): Promise<ListNodesResponse> => {
  data = nodeModelsSchemaResponseTransformer(data);
  return data;
};

export const createNodeResponseTransformer = async (
  data: any
): Promise<CreateNodeResponse> => {
  data = nodeModelSchemaResponseTransformer(data);
  return data;
};

export const getNodeByIdResponseTransformer = async (
  data: any
): Promise<GetNodeByIdResponse> => {
  data = nodeModelSchemaResponseTransformer(data);
  return data;
};

const workflowModelSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const workflowModelsSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => {
    return workflowModelSchemaResponseTransformer(item);
  });
  return data;
};

export const listWorkflowsResponseTransformer = async (
  data: any
): Promise<ListWorkflowsResponse> => {
  data = workflowModelsSchemaResponseTransformer(data);
  return data;
};

export const createWorkflowResponseTransformer = async (
  data: any
): Promise<CreateWorkflowResponse> => {
  data = workflowModelSchemaResponseTransformer(data);
  return data;
};

export const getWorkflowByIdResponseTransformer = async (
  data: any
): Promise<GetWorkflowByIdResponse> => {
  data = workflowModelSchemaResponseTransformer(data);
  return data;
};

export const updateWorkflowResponseTransformer = async (
  data: any
): Promise<UpdateWorkflowResponse> => {
  data = workflowModelSchemaResponseTransformer(data);
  return data;
};
