// This file is auto-generated by @hey-api/openapi-ts

export type Annotation = {
  description: string;
  version: string;
};

export type ComponentProperties = {
  image: string;
  metadata: WorkflowStepMetadata;
  parameters?: {} | null;
};

export type CreateNodeInputSchema = {
  icon: Blob | File;
  node_def: NodeDef;
  wasm_file: Blob | File;
};

export type CreateWorkflow = {
  workflow_def: WorkflowDef;
};

export type Deployment = {
  deployment_id: string;
  manifest_name?: string | null;
  manifest_version?: string | null;
  status:
    | 'Created'
    | 'Submitted'
    | 'Validated'
    | 'Processed'
    | 'Deployed'
    | 'Cancelled';
  workflow_id: string;
};

export type Deployments = Array<Deployment>;

export type ErrorType =
  | {
      type: 'NotFound';
    }
  | {
      type: 'BadRequest';
    }
  | {
      type: 'InternalServerError';
    }
  | {
      type: 'Conflict';
    }
  | {
      type: 'Unauthorized';
    }
  | {
      type: 'WorkflowNotDeployed';
    };

export type Executions = Array<Model>;

export type HashMap = {
  [key: string]: Array<string>;
};

export type Metadata = {
  annotations?: null | Annotation;
  name: string;
};

export type Model = {
  created_at: Date;
  id: string;
  result?: null | Value;
  run_id: string;
  started: boolean;
  status: string;
  updated_at: Date;
  workflow_id: string;
};

export type NodeAnnotation = {
  color: string;
  description: string;
  icon: string;
  label: string;
  ui: string;
  version: string;
};

export type NodeDef = {
  api_version: string;
  metadata: NodeMetadata;
  spec: NodeSpec;
};

export type NodeMetadata = {
  annotations: NodeAnnotation;
  name: string;
};

export type NodeModel = {
  created_at: Date;
  id: string;
  image: string;
  node_def: NodeDef;
  updated_at: Date;
};

export type NodeModels = Array<NodeModel>;

export type NodeParameter =
  | {
      default: string;
      description: string;
      type: 'string';
    }
  | {
      default: number;
      description: string;
      type: 'number';
    }
  | {
      default: number;
      description: string;
      type: 'integer';
    }
  | {
      default: boolean;
      description: string;
      type: 'boolean';
    }
  | {
      default: {
        [key: string]: string;
      };
      description: string;
      type: 'object';
    }
  | {
      default: Array<string>;
      description: string;
      type: 'array';
    };

export type NodeParameterDefinition = {
  validation_schema: ValidationSchema;
};

export type NodeSpec = {
  properties: Properties;
};

export type OpenApiError = ErrorType & {
  details?: null | HashMap;
  message: string;
};

export type Position = {
  x: number;
  y: number;
};

export type Properties = {
  parameters: NodeParameterDefinition;
};

export type ProviderProperties = {
  image: string;
};

export type SuccessResponse = {
  success: boolean;
};

export type UpdateWorkflow = {
  workflow_def: WorkflowDef;
};

export type ValidationSchema = {
  properties: {
    [key: string]: NodeParameter;
  };
  required: Array<string>;
};

export type Value = unknown;

export type WorkflowDef = {
  api_version: string;
  metadata: Metadata;
  spec: WorkflowSpec;
};

export type WorkflowModel = {
  created_at: Date;
  deployment_id?: string | null;
  id: string;
  manifest_name?: string | null;
  updated_at: Date;
  workflow_def: WorkflowDef;
};

export type WorkflowModels = Array<WorkflowModel>;

export type WorkflowSpec = {
  drafts: Array<WorkflowStep>;
  steps: Array<WorkflowStep>;
};

export type WorkflowStep = WorkflowStepProperties & {
  name: string;
};

export type WorkflowStepMetadata = {
  position: Position;
};

export type WorkflowStepProperties =
  | {
      properties: ComponentProperties;
      type: 'component';
    }
  | {
      properties: ProviderProperties;
      type: 'provider';
    };

export type ListDeploymentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/deployments';
};

export type ListDeploymentsErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type ListDeploymentsError =
  ListDeploymentsErrors[keyof ListDeploymentsErrors];

export type ListDeploymentsResponses = {
  /**
   * Done
   */
  200: Deployments;
};

export type ListDeploymentsResponse =
  ListDeploymentsResponses[keyof ListDeploymentsResponses];

export type DeleteDeploymentData = {
  body?: never;
  path: {
    /**
     * Deployment ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/deployments/{id}';
};

export type DeleteDeploymentErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type DeleteDeploymentError =
  DeleteDeploymentErrors[keyof DeleteDeploymentErrors];

export type DeleteDeploymentResponses = {
  /**
   * Done
   */
  200: SuccessResponse;
};

export type DeleteDeploymentResponse =
  DeleteDeploymentResponses[keyof DeleteDeploymentResponses];

export type GetDeploymentData = {
  body?: never;
  path: {
    /**
     * Deployment ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/deployments/{id}';
};

export type GetDeploymentErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type GetDeploymentError = GetDeploymentErrors[keyof GetDeploymentErrors];

export type GetDeploymentResponses = {
  /**
   * Done
   */
  200: Deployment;
};

export type GetDeploymentResponse =
  GetDeploymentResponses[keyof GetDeploymentResponses];

export type ListExecutionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/executions';
};

export type ListExecutionsErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type ListExecutionsError =
  ListExecutionsErrors[keyof ListExecutionsErrors];

export type ListExecutionsResponses = {
  /**
   * Done
   */
  200: Executions;
};

export type ListExecutionsResponse =
  ListExecutionsResponses[keyof ListExecutionsResponses];

export type DeleteExecutionsData = {
  body?: never;
  path: {
    /**
     * Execution ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/executions/{id}';
};

export type DeleteExecutionsErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type DeleteExecutionsError =
  DeleteExecutionsErrors[keyof DeleteExecutionsErrors];

export type DeleteExecutionsResponses = {
  /**
   * Done
   */
  200: SuccessResponse;
};

export type DeleteExecutionsResponse =
  DeleteExecutionsResponses[keyof DeleteExecutionsResponses];

export type GetExecutionData = {
  body?: never;
  path: {
    /**
     * Execution ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/executions/{id}';
};

export type GetExecutionErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type GetExecutionError = GetExecutionErrors[keyof GetExecutionErrors];

export type GetExecutionResponses = {
  /**
   * Done
   */
  200: Model;
};

export type GetExecutionResponse =
  GetExecutionResponses[keyof GetExecutionResponses];

export type ListNodesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/nodes';
};

export type ListNodesErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type ListNodesError = ListNodesErrors[keyof ListNodesErrors];

export type ListNodesResponses = {
  /**
   * Done
   */
  200: NodeModels;
};

export type ListNodesResponse = ListNodesResponses[keyof ListNodesResponses];

export type CreateNodeData = {
  body: CreateNodeInputSchema;
  path?: never;
  query?: never;
  url: '/api/v1/nodes';
};

export type CreateNodeErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type CreateNodeError = CreateNodeErrors[keyof CreateNodeErrors];

export type CreateNodeResponses = {
  /**
   * Created
   */
  201: NodeModel;
};

export type CreateNodeResponse = CreateNodeResponses[keyof CreateNodeResponses];

export type GetNodeByIdData = {
  body?: never;
  path: {
    /**
     * Node ID
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/nodes/{id}';
};

export type GetNodeByIdErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type GetNodeByIdError = GetNodeByIdErrors[keyof GetNodeByIdErrors];

export type GetNodeByIdResponses = {
  /**
   * Done
   */
  200: NodeModel;
};

export type GetNodeByIdResponse =
  GetNodeByIdResponses[keyof GetNodeByIdResponses];

export type ListWorkflowsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/workflows';
};

export type ListWorkflowsErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type ListWorkflowsError = ListWorkflowsErrors[keyof ListWorkflowsErrors];

export type ListWorkflowsResponses = {
  /**
   * Done
   */
  200: WorkflowModels;
};

export type ListWorkflowsResponse =
  ListWorkflowsResponses[keyof ListWorkflowsResponses];

export type CreateWorkflowData = {
  body: CreateWorkflow;
  path?: never;
  query?: never;
  url: '/api/v1/workflows';
};

export type CreateWorkflowErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type CreateWorkflowError =
  CreateWorkflowErrors[keyof CreateWorkflowErrors];

export type CreateWorkflowResponses = {
  /**
   * Created
   */
  201: WorkflowModel;
};

export type CreateWorkflowResponse =
  CreateWorkflowResponses[keyof CreateWorkflowResponses];

export type DeleteWorkflowData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/workflows/{id}';
};

export type DeleteWorkflowErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type DeleteWorkflowError =
  DeleteWorkflowErrors[keyof DeleteWorkflowErrors];

export type DeleteWorkflowResponses = {
  /**
   * Done
   */
  200: SuccessResponse;
};

export type DeleteWorkflowResponse =
  DeleteWorkflowResponses[keyof DeleteWorkflowResponses];

export type GetWorkflowByIdData = {
  body?: never;
  path: {
    /**
     * Workflow id
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/workflows/{id}';
};

export type GetWorkflowByIdErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type GetWorkflowByIdError =
  GetWorkflowByIdErrors[keyof GetWorkflowByIdErrors];

export type GetWorkflowByIdResponses = {
  /**
   * Done
   */
  200: WorkflowModel;
};

export type GetWorkflowByIdResponse =
  GetWorkflowByIdResponses[keyof GetWorkflowByIdResponses];

export type UpdateWorkflowData = {
  body: UpdateWorkflow;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/workflows/{id}';
};

export type UpdateWorkflowErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type UpdateWorkflowError =
  UpdateWorkflowErrors[keyof UpdateWorkflowErrors];

export type UpdateWorkflowResponses = {
  /**
   * Done
   */
  200: WorkflowModel;
};

export type UpdateWorkflowResponse =
  UpdateWorkflowResponses[keyof UpdateWorkflowResponses];

export type DeployWorkflowData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/workflows/{id}/deploy';
};

export type DeployWorkflowErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type DeployWorkflowError =
  DeployWorkflowErrors[keyof DeployWorkflowErrors];

export type DeployWorkflowResponses = {
  /**
   * Done
   */
  200: SuccessResponse;
};

export type DeployWorkflowResponse =
  DeployWorkflowResponses[keyof DeployWorkflowResponses];

export type RunWorkflowData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/workflows/{id}/run';
};

export type RunWorkflowErrors = {
  /**
   * Bad Request
   */
  400: OpenApiError;
  /**
   * Not Found
   */
  404: OpenApiError;
  /**
   * Conflict
   */
  409: OpenApiError;
  /**
   * Internal Server Error
   */
  500: OpenApiError;
};

export type RunWorkflowError = RunWorkflowErrors[keyof RunWorkflowErrors];

export type RunWorkflowResponses = {
  /**
   * Done
   */
  200: SuccessResponse;
};

export type RunWorkflowResponse =
  RunWorkflowResponses[keyof RunWorkflowResponses];

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};
